In [ ]:
# MATEMÁTICA E ESTATÍSTICA BÁSICA

# numpy -> facilita a rápida execução de cálculos matemáticos e estatísticos em
# arrays e matrizes mesmo com uma grande quantidade de observações;

# array -> é um conjunto unidimensional onde todos os elementos são do mesmo tipo.



In [ ]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [ ]:
# visualização de até números com até duas casas decimais
np.set_printoptions(precision=2)

In [ ]:
# criação de um array - modo simples
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
from numpy import random
# criação de um array por atribuição
np.random.seed(25)
b = randn(6)
b

array([ 0.23,  1.03, -0.84, -0.59, -0.96, -0.22])

In [ ]:
c = np.arange(1, 35)
c 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [ ]:
# fazendo operações aritméticas com os arrays
a + b
a * 10
a / b 



array([  4.38,   1.95,  -3.57,  -6.77,  -5.23, -26.99])

In [ ]:
# Diferente de array, matrizes são objetos que contém conjuntos de dados
# bi-dimensionais que contém elementos armazenados em arrays - são arrays de arrays;

# multiplicação de matrizes e arrays
a = np.arange(3)
a

aa = np.array([[2., 4., 6.], [1., 3., 5.], [10., 20., 30]])
aa

a * aa

array([[ 0.,  4., 12.],
       [ 0.,  3., 10.],
       [ 0., 20., 60.]])

In [ ]:
bb = np.arange(9).reshape((3,3))
bb

aa * bb

# perceba que a multiplicação abaixo não é a multiplicação de matrizes que conhecemos
# o que aconteceu foi que quando usamos o simbolo de * o numpy achou que nós precisavámos
# multiplicar item a item das duas matrizes.
# mas o que queremos é fazer a MULTIPLICAÇÃO DE MATRIZES. Para isso use o metódo .dot 

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [ ]:
np.dot(aa, bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])

In [ ]:
# metódo do escalar
b = a * 3
b

np.dot(a,b)

15